apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    costcenter: amer
    location: NA
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

