apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-quota-dep
  namespace: cm-webinar 
spec:
  replicas: 4
  selector:
    matchLabels:
      run: nginx-quota-dep
  template:
    metadata:
      labels:
        run: nginx-quota-dep
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          requests:        
            memory: "250M"
            cpu: "0.25"
          limits:
            memory: "250M"
            cpu: "0.25"
